### ISSUE TITLE
Add support for keyboard input

### ISSUE THREAD

**Issue by schickling** [Effect-TS/cli#164]
It would be great if it was easy to implement keyboard input features (such as keyboard shortcuts e.g. for dev servers).

## Related

- https://github.com/contentlayerdev/contentlayer/issues/49

**Comment by IMax153** [comment]
This is now possible, but involves creating custom `Prompt` types so it is not trivial. `@effect/cli` does however ship with several builtin prompt types.

**Comment by schickling** [comment]
That's awesome! 🎉 

Would be great to have an example for this as well :)
