### ISSUE TITLE
Args and Options Schema validation 

### ISSUE THREAD

**Issue by fubhy** [Effect-TS/cli#419]
1) I often need to validate options & args more strictly. It'd be great if I could use `@effect/schema` here.

2) In some instances, I also need to validate options and args against one another. How'd we do that here?

3) Additional, I sometimes have to protect against absurd combinations of user-provided options (providing option `A` means that `B` cannot be provided and should error). This would quickly get out of hand if I'd model that as a union of allowed combinations. AFAIK schema doesn't offer a solution for that either. Do we want to cover this too?

A `.withSchema` combinator would be a good start for the individual options and args.

I'm not quite sure how we'd do items 2) and 3) of my wishlist

**Comment by tim-smart** [comment]
With the added provide apis you can do this:

```ts
import { Schema } from "@effect/schema"
import { Context, Effect } from "effect"
import { Command, Options } from "@effect/cli"

const customArgs = Schema.struct({
  verbose: Schema.boolean,
})
interface CustomArgs {
  readonly _: unique symbol
}
const CustomArgs = Context.Tag<
  CustomArgs,
  Schema.Schema.To<typeof customArgs>
>()

const schemaCommand = Command.make("schema", {
  verbose: Options.boolean("verbose"),
}).pipe(
  Command.withHandler(() =>
    Effect.gen(function* (_) {
      const args: { readonly verbose: boolean } = yield* _(CustomArgs)
    }),
  ),
  Command.provideEffect(CustomArgs, (_) => Schema.decode(customArgs)(_)),
)
```

**Comment by strogonoff** [comment]
This may not be directly related, but I’m curious whether it’s possible to achieve this without duplicating `Schema.struct({ verbose: Schema.boolean })`+ `{ verbose: Options.boolean('verbose') }`. I suppose converting a schema to options would require traversing & inspecting schema properties to determine (and simplify) their type… A simple transform would not be possible if Options have nothing in common with Schema, I suppose.

**Comment by fubhy** [comment]
@strogonoff Closing this as Tim's answer is sufficient for my use case (after the addition of the `provideEffect` APIs). Please open another issue if your question is still relevant! Thank you :)
